### PR TITLE
Very pleasant updates that bring happiness

### PR DESCRIPTION
**Pull request by lindsaymarkward**
Joyous documentation improvements resulting in smiles, especially for those enabling SSH access.

### CODE REVIEW

**Comment by elliots** [comment]
Uh... while awesome additions, why are there 44 commits?

**Comment by wolfeidau** [comment]
Merged this manually as it conflicted with some @jonseymour had added in new and amazing ways.

Fun times with git.

Thanks for the copy and tweaks.

**Comment by lindsaymarkward** [comment]
@elliots , I'm not sure. Probably from trying to keep my fork up to date with the upstream repo. I've been using IntelliJ, so I rebased my fork, then updated the project, then pushed it up to GitHub. Perhaps there's a better way I'm missing...

**Comment by lindsaymarkward** [comment]
When does the live documentation get updated? Do you have to merge develop into master for this?

**Comment by wolfeidau** [comment]
I have to manually push it at the moment, this will happen in the next couple of days.

Working on open sourcing projects at the moment.

**Comment by lindsaymarkward** [comment]
I'm sure you have many other more important things now, but I was wondering if this was going to get pushed manually to the live docs website? Thanks.

**Pull request merged**
